### ISSUE TITLE
Compatibility issue between unstructured[pdf]==0.16.11 and pdfminer.six 20250327

### ISSUE THREAD

**Issue by Badribn0612** [Unstructured-IO/unstructured#3982]
Description:
When installing unstructured[pdf]==0.16.11, it pulls in the latest pdfminer.six 20250327, which causes import errors.

Steps to reproduce:
1. pip install "unstructured[pdf]==0.16.11"
2. Run the following code:

```python
from langchain_community.document_loaders import UnstructuredPDFLoader

doc = './IF10244.pdf'
loader = UnstructuredPDFLoader(file_path=doc,
                               strategy='hi_res',
                               extract_images_in_pdf=True,
                               infer_table_structure=True,
                               mode='elements',
                               image_output_dir_path='./figures')
data = loader.load()

Error:
ImportError: cannot import name 'PSSyntaxError' from 'pdfminer.pdfparser' (/usr/local/lib/python3.11/dist-packages/pdfminer/pdfparser.py)

The issue appears to be that unstructured is trying to import PSSyntaxError from pdfminer.pdfparser, but this class isn't available in the newest version of pdfminer.six.
Workaround:
Downgrading pdfminer.six resolves the issue:
pip install pdfminer.six==20240706

Environment:
Python version: 3.11
OS: [linux]
unstructured: 0.16.11
pdfminer.six: 20250327 (fails), 20240706 (works)

**Comment by buffliu** [comment]
HAVE ANYBODY SOLVE THIS ISSUE?

**Comment by robot-stefan** [comment]
The setup I have listed in https://github.com/robot-stefan/langchain-rag/blob/main/requirements.txt also works on python 3.10 just ran into this migrating and pulling packages for new venv . Hope this helps others.

**Comment by deepakdhiman7** [comment]
> pip install pdfminer.six==20240706

Thank you so much. It worked! :)

**Comment by jbbqqf** [comment]
Hi! Triaging older bug reports — I think this one is already shipped and can be closed.

The original report (April 2025) was on `unstructured[pdf]==0.16.11` with `pdfminer.six 20250327`, hitting `ImportError: cannot import name 'PSSyntaxError' from 'pdfminer.pdfparser'`.

Evidence the fix has landed:

- [`CHANGELOG.md` line 829 (0.17.5)](https://github.com/Unstructured-IO/unstructured/blob/main/CHANGELOG.md#L829): *"Fix for 'PSSyntaxError' import error: 'cannot import name PSSyntaxError from pdfminer.pdfparser' — PSSyntaxError needed to be imported from its source 'pdfminer.psexceptions'."*
- [`unstructured/partition/pdf_image/pdfminer_utils.py:21`](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/pdf_image/pdfminer_utils.py#L21) on `main` now reads `from pdfminer.psexceptions import PSSyntaxError` — the symbol's actual home, so the import works against current `pdfminer.six`.
- [`pyproject.toml:67`](https://github.com/Unstructured-IO/unstructured/blob/main/pyproject.toml#L67) pins `pdfminer.six>=20251230, <20270000`, well past the `20250327` build the reporter was on.

So upgrading to ≥ 0.17.5 (today's `main` is much further along) makes this go away. If I'm wrong about the reproducer being version-bound, point me at a `main`-reproducible variant and I'll dig further. Otherwise it looks safe to close.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against `main`.*
