### PR TITLE
fix(partition): skip ProcessingInstruction nodes in HTML parser

### LINKED ISSUE #4358: bug/xml indentation causes parsing error
**Describe the bug**
This error occurs when xml opening tags are on the same level as the xml context itself

'lxml.etree._ProcessingInstruction' object has no attribute 'is_phrasing'

This breaks
```
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
```
This succeeds
```
```xml
   <?xml version="1.0" encoding="UTF-8"?>
```

**To Reproduce**
Use unstructured to process a markdown file that contains an xml block with the opening tags on the same level as the start of the content

**Expected behavior**
This should not be a breaking format, it should continue in the same way as is the xml opening tag was tabbed back

**Screenshots**

**Environment Info**
Please run `python scripts/collect_env.py` and paste the output here. 
I am running unstructured version 0.18.24

### PR DESCRIPTION
**Pull request by michaelxer**
## Summary

Fixes #4358

The HTML parser raises `AttributeError: '_ProcessingInstruction' object has no attribute 'is_phrasing'` when lxml injects `ProcessingInstruction` or `_Comment` nodes into the element tree. This is a regression of #3578 (the fix from PR #4034 was lost during a refactor).

## Root Cause

`Flow.iter_elements()`, `Phrasing._iter_child_text_segments()`, and `Anchor._iter_phrases_and_elements()` build a deque from `self` children and access `.is_phrasing` on each — but PI/Comment nodes bypass lxml's `ElementNamespaceClassLookup` and are raw lxml types without that attribute.

## Fix

Filter children to only `Flow`/`Phrasing` instances at all three `deque(self)` call sites (lines 370, 641, 743). Non-Element nodes (PI, Comment) are silently skipped.

## Test

Added `DescribeProcessingInstructionHandling` with two tests verifying PI nodes in both flow and phrasing contexts don't crash the parser. All 135 tests pass.

---
## Summary by cubic
Prevent HTML parser crashes when `lxml` injects ProcessingInstruction or comment nodes by skipping non-`Flow`/`Phrasing` children during iteration. This fixes AttributeError on nodes without `is_phrasing` and keeps parsing stable.

- **Bug Fixes**
  - Filter non-`Flow`/`Phrasing` children when queuing in `Flow.iter_elements`, `Phrasing._iter_child_text_segments`, and `Anchor._iter_phrases_and_elements`.
  - Add tests covering PI nodes in flow and phrasing contexts; update changelog.

<sup>Written for commit 52877bbddfd03502ff1850467b6899f4cd187375. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/Unstructured-IO/unstructured/pull/4362?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Comment by michaelxer** [comment]
Cleaning up PR portfolio. Fix is still valid if maintainers are interested.
