### ISSUE TITLE
error in docx partition

### ISSUE THREAD

**Issue by lucas-labs** [Unstructured-IO/unstructured#775]
After updating from 0.7.5 to 0.7.6, I'm getting an error when trying to parse a docx file.

```bash
'lxml.etree._Element' object has no attribute 'xml'
``` 

I tracked the error to the following line. Apparently not every element has an `xml` attribute:

https://github.com/Unstructured-IO/unstructured/blob/743482b6d3ea8dd03bf029c9c7f62ceb095e0dfc/unstructured/partition/docx.py#L224-L225

**Comment by MthwRobinson** [comment]
@lucas-labs - Thanks for reporting this, will get this fixed ASAP.

**Comment by MthwRobinson** [comment]
@lucas-labs - This should be fixed in `0.7.7`. Thanks!!
